version: 2.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
before_build:
- ps: .\.appveyor\appveyor.before-build.ps1
build:
  project: .\.build\Build.msbuild
  verbosity: normal
after_build:
- ps: .\.appveyor\appveyor.after-build.ps1
artifacts:
- path: '**\bin\**\*.zip'
  name: Zip
before_deploy:
- ps: .\.appveyor\appveyor.before-deployment.ps1
deploy:
- provider: GitHub
  tag: $(APPVEYOR_PROJECT_NAME)-v$(CI_BUILD_VERSION)
  release: $(APPVEYOR_PROJECT_NAME)-v$(CI_BUILD_VERSION)
  auth_token:
    secure: UEgy2H9zJKLi599QoO3qVf5BKFqloRQ246ez9cEgsfV3vooAUfVopMS9+IjRtArL
  artifact: Zip
  on:
    branch: master
    CI_DEPLOY_GITHUB: True
after_deploy:
- ps: .\.appveyor\appveyor.after-deployment.ps1